# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedditTest-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedditTest-ios

  target 'RedditTest-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedditTest-iosUITests' do
    # Pods for testing
  end

end
